stages:
  - build
  - publish

build:
  stage: build
  image: mbed/yotta
  script:
    - yt build

documentation:
  stage: build
  image: hrektts/doxygen
  script:
    - doxygen
    - ls doc
  artifacts:
    paths:
    - doc/html/

pages:
  stage: publish
  image: alpine
  script:
    - mv doc/html/ public/
  artifacts:
    paths:
    - public
