name: ci
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: docker://mbed/yotta
        with:
          entrypoint: /bin/sh
          args: yt build
